apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    repoURL: ssh://git@gitea-ssh.gitea.svc.cluster.local:22/platform/policies.git
    targetRevision: main
    path: cluster-policies/kyverno
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - '.spec.rules[] | select(.name | startswith("autogen-"))'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
