apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: policy-reporter
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kyverno.github.io/policy-reporter
    chart: policy-reporter
    targetRevision: "*"
    helm:
      releaseName: policy-reporter
      values: |
        ui:
          enabled: true
        plugin:
          kyverno:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
