apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-actions-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: gitea-runner
    server: https://kubernetes.default.svc
  source:
    repoURL: ssh://git@gitea-ssh.gitea.svc.cluster.local:22/platform/policies.git
    targetRevision: main
    path: apps/gitea-actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
