apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "69"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  source:
    repoURL: cr.agentgateway.dev/charts
    chart: agentgateway
    targetRevision: v1.2.0
    helm:
      releaseName: agentgateway
      skipCrds: false
      values: |
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
      parameters:
        - name: controller.extraEnv.KGW_ENABLE_GATEWAY_API_EXPERIMENTAL_FEATURES
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
