apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatgpt-sim
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "80"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/platform/platform-policies.git
    targetRevision: main
    path: apps/chatgpt-sim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
