apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "80"
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/managed-by: argocd
    role: shared
