apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  annotations:
    argocd.argoproj.io/sync-wave: "86"
  labels:
    app.kubernetes.io/name: argo-rollouts
    platform.publiccloudexperiments.net/namespace-role: platform
    kyverno.io/isolate: "true"
