apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "87"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.41.0
    helm:
      releaseName: argo-rollouts
      values: |
        controller:
          image:
            registry: quay.io
            repository: argoproj/argo-rollouts
            tag: v1.9.0
          initContainers:
            - name: install-gatewayapi-plugin
              image: host.docker.internal:5002/platform/argo-rollouts-gatewayapi-plugin:v0.5.0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - cp /plugins/gatewayapi-plugin /plugins-target/gatewayapi-plugin && chmod 0755 /plugins-target/gatewayapi-plugin
              volumeMounts:
                - name: trafficrouter-plugins
                  mountPath: /plugins-target
          volumeMounts:
            - name: trafficrouter-plugins
              mountPath: /var/run/argo-rollouts/plugins
          volumes:
            - name: trafficrouter-plugins
              emptyDir: {}
          trafficRouterPlugins:
            - name: argoproj-labs/gatewayAPI
              location: file:///var/run/argo-rollouts/plugins/gatewayapi-plugin
        dashboard:
          enabled: true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
