apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "88"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.1
    helm:
      releaseName: metrics-server
      values: |
        image:
          repository: registry.k8s.io/metrics-server/metrics-server
          tag: v0.8.1
        args:
          - --kubelet-insecure-tls
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 250m
            memory: 300Mi
        podLabels:
          app.kubernetes.io/part-of: platform-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
