#!/usr/bin/env bash

stack_env_init() {
  STACK_SLOT_WIDTH="${STACK_SLOT_WIDTH:-100}"

  if [[ -n "${STACK_SLOT:-}" && -z "${PORT_OFFSET:-}" ]]; then
    PORT_OFFSET="$((STACK_SLOT * STACK_SLOT_WIDTH))"
  fi
  PORT_OFFSET="${PORT_OFFSET:-0}"

  url_port_suffix() {
    case "$1" in
      80|443) printf '' ;;
      *) printf ':%s' "$1" ;;
    esac
  }

  APIM_GATEWAY_PORT="${APIM_GATEWAY_PORT:-$((8000 + PORT_OFFSET))}"
  GRAFANA_HOST="${GRAFANA_HOST:-lgtm.apim.127.0.0.1.sslip.io}"
  GRAFANA_PORT="${GRAFANA_PORT:-$((8443 + PORT_OFFSET))}"
  OTEL_GRPC_PORT="${OTEL_GRPC_PORT:-$((4317 + PORT_OFFSET))}"
  OTEL_HTTP_PORT="${OTEL_HTTP_PORT:-$((4318 + PORT_OFFSET))}"
  KEYCLOAK_PORT="${KEYCLOAK_PORT:-$((8180 + PORT_OFFSET))}"
  OPERATOR_CONSOLE_PORT="${OPERATOR_CONSOLE_PORT:-$((3007 + PORT_OFFSET))}"
  EDGE_HTTP_PORT="${EDGE_HTTP_PORT:-$((8088 + PORT_OFFSET))}"
  EDGE_TLS_HTTP_PORT="${EDGE_TLS_HTTP_PORT:-$((8080 + PORT_OFFSET))}"
  EDGE_TLS_PORT="${EDGE_TLS_PORT:-$((9443 + PORT_OFFSET))}"
  TODO_FRONTEND_PORT="${TODO_FRONTEND_PORT:-$((3000 + PORT_OFFSET))}"
  VITE_DEV_PORT="${VITE_DEV_PORT:-5173}"

  APIM_BASE_URL="${APIM_BASE_URL:-http://localhost:${APIM_GATEWAY_PORT}}"
  APIM_LOOPBACK_BASE_URL="${APIM_LOOPBACK_BASE_URL:-http://127.0.0.1:${APIM_GATEWAY_PORT}}"
  GRAFANA_BASE_URL="${GRAFANA_BASE_URL:-https://${GRAFANA_HOST}$(url_port_suffix "$GRAFANA_PORT")}"
  KEYCLOAK_BASE_URL="${KEYCLOAK_BASE_URL:-http://localhost:${KEYCLOAK_PORT}}"
  OIDC_ISSUER_EXTERNAL="${OIDC_ISSUER_EXTERNAL:-${KEYCLOAK_BASE_URL}/realms/subnet-calculator}"
  OPERATOR_CONSOLE_URL="${OPERATOR_CONSOLE_URL:-http://localhost:${OPERATOR_CONSOLE_PORT}}"
  TODO_FRONTEND_BASE_URL="${TODO_FRONTEND_BASE_URL:-http://127.0.0.1:${TODO_FRONTEND_PORT}}"
  TODO_FRONTEND_BROWSER_URL="${TODO_FRONTEND_BROWSER_URL:-http://localhost:${TODO_FRONTEND_PORT}}"
  TODO_FRONTEND_ORIGIN_LOCALHOST="${TODO_FRONTEND_ORIGIN_LOCALHOST:-http://localhost:${TODO_FRONTEND_PORT}}"
  TODO_FRONTEND_ORIGIN_LOOPBACK="${TODO_FRONTEND_ORIGIN_LOOPBACK:-http://127.0.0.1:${TODO_FRONTEND_PORT}}"
  TODO_APIM_BASE_URL="${TODO_APIM_BASE_URL:-${APIM_LOOPBACK_BASE_URL}}"
  TODO_APIM_PUBLIC_BASE_URL="${TODO_APIM_PUBLIC_BASE_URL:-${APIM_BASE_URL}}"
  TODO_GRAFANA_BASE_URL="${TODO_GRAFANA_BASE_URL:-${GRAFANA_BASE_URL}}"
  TODO_OBSERVABILITY_DASHBOARD_URL="${TODO_OBSERVABILITY_DASHBOARD_URL:-${GRAFANA_BASE_URL}/d/apim-simulator-overview/apim-simulator-overview}"
  APIM_ALLOWED_ORIGIN_BROWSER_LOCALHOST="${APIM_ALLOWED_ORIGIN_BROWSER_LOCALHOST:-${TODO_FRONTEND_ORIGIN_LOCALHOST}}"
  APIM_ALLOWED_ORIGIN_OPERATOR_CONSOLE="${APIM_ALLOWED_ORIGIN_OPERATOR_CONSOLE:-${OPERATOR_CONSOLE_URL}}"
  APIM_ALLOWED_ORIGIN_VITE="${APIM_ALLOWED_ORIGIN_VITE:-http://localhost:${VITE_DEV_PORT}}"
  APIM_ALLOWED_ORIGIN_GATEWAY="${APIM_ALLOWED_ORIGIN_GATEWAY:-${APIM_BASE_URL}}"
  SMOKE_HELLO_BASE_URL="${SMOKE_HELLO_BASE_URL:-${APIM_LOOPBACK_BASE_URL}}"
  SMOKE_HELLO_KEYCLOAK_BASE_URL="${SMOKE_HELLO_KEYCLOAK_BASE_URL:-${KEYCLOAK_BASE_URL}}"
  SMOKE_OIDC_BASE_URL="${SMOKE_OIDC_BASE_URL:-${APIM_LOOPBACK_BASE_URL}}"
  SMOKE_OIDC_KEYCLOAK_BASE_URL="${SMOKE_OIDC_KEYCLOAK_BASE_URL:-${KEYCLOAK_BASE_URL}}"
  APIM_EDGE_ROOT_HOST="${APIM_EDGE_ROOT_HOST:-apim.127.0.0.1.sslip.io}"
  APIM_EDGE_HOST="${APIM_EDGE_HOST:-edge.apim.127.0.0.1.sslip.io}"
  APIM_EDGE_WILDCARD_HOST="${APIM_EDGE_WILDCARD_HOST:-*.apim.127.0.0.1.sslip.io}"
  EDGE_HTTP_BASE_URL="${EDGE_HTTP_BASE_URL:-http://${APIM_EDGE_HOST}:${EDGE_HTTP_PORT}}"
  EDGE_TLS_BASE_URL="${EDGE_TLS_BASE_URL:-https://${APIM_EDGE_HOST}:${EDGE_TLS_PORT}}"

  STACK_INSTANCE_SUFFIX="${STACK_INSTANCE_SUFFIX:-}"
  if [[ -z "$STACK_INSTANCE_SUFFIX" ]]; then
    if [[ -n "${STACK_SLOT:-}" ]]; then
      STACK_INSTANCE_SUFFIX="s${STACK_SLOT}"
    elif [[ "$PORT_OFFSET" != "0" ]]; then
      STACK_INSTANCE_SUFFIX="o${PORT_OFFSET}"
    fi
  fi

  export STACK_SLOT STACK_SLOT_WIDTH PORT_OFFSET STACK_INSTANCE_SUFFIX
  export APIM_GATEWAY_PORT GRAFANA_HOST GRAFANA_PORT OTEL_GRPC_PORT OTEL_HTTP_PORT KEYCLOAK_PORT OPERATOR_CONSOLE_PORT EDGE_HTTP_PORT EDGE_TLS_HTTP_PORT EDGE_TLS_PORT TODO_FRONTEND_PORT VITE_DEV_PORT
  export APIM_BASE_URL APIM_LOOPBACK_BASE_URL GRAFANA_BASE_URL KEYCLOAK_BASE_URL OIDC_ISSUER_EXTERNAL OPERATOR_CONSOLE_URL
  export TODO_FRONTEND_BASE_URL TODO_FRONTEND_BROWSER_URL TODO_FRONTEND_ORIGIN_LOCALHOST TODO_FRONTEND_ORIGIN_LOOPBACK TODO_APIM_BASE_URL TODO_APIM_PUBLIC_BASE_URL TODO_GRAFANA_BASE_URL TODO_OBSERVABILITY_DASHBOARD_URL
  export APIM_ALLOWED_ORIGIN_BROWSER_LOCALHOST APIM_ALLOWED_ORIGIN_OPERATOR_CONSOLE APIM_ALLOWED_ORIGIN_VITE APIM_ALLOWED_ORIGIN_GATEWAY
  export APIM_EDGE_ROOT_HOST APIM_EDGE_HOST APIM_EDGE_WILDCARD_HOST
  export SMOKE_HELLO_BASE_URL SMOKE_HELLO_KEYCLOAK_BASE_URL SMOKE_OIDC_BASE_URL SMOKE_OIDC_KEYCLOAK_BASE_URL EDGE_HTTP_BASE_URL EDGE_TLS_BASE_URL
}

stack_env_display_path() {
  local path="$1"
  local root_prefix

  if [[ -z "${ROOT_DIR:-}" ]]; then
    printf '%s' "$path"
    return 0
  fi

  if [[ "$path" == "$ROOT_DIR" ]]; then
    printf '.'
    return 0
  fi

  root_prefix="$ROOT_DIR/"
  if [[ "$path" == "$root_prefix"* ]]; then
    printf './%s' "${path#"$root_prefix"}"
    return 0
  fi

  printf '%s' "$path"
}

stack_env_print_exports() {
  local name
  for name in \
    STACK_SLOT STACK_SLOT_WIDTH PORT_OFFSET STACK_INSTANCE_SUFFIX \
    APIM_GATEWAY_PORT GRAFANA_HOST GRAFANA_PORT OTEL_GRPC_PORT OTEL_HTTP_PORT KEYCLOAK_PORT OPERATOR_CONSOLE_PORT EDGE_HTTP_PORT EDGE_TLS_HTTP_PORT EDGE_TLS_PORT TODO_FRONTEND_PORT VITE_DEV_PORT \
    APIM_BASE_URL APIM_LOOPBACK_BASE_URL GRAFANA_BASE_URL KEYCLOAK_BASE_URL OIDC_ISSUER_EXTERNAL OPERATOR_CONSOLE_URL \
    TODO_FRONTEND_BASE_URL TODO_FRONTEND_BROWSER_URL TODO_FRONTEND_ORIGIN_LOCALHOST TODO_FRONTEND_ORIGIN_LOOPBACK TODO_APIM_BASE_URL TODO_APIM_PUBLIC_BASE_URL TODO_GRAFANA_BASE_URL TODO_OBSERVABILITY_DASHBOARD_URL \
    APIM_ALLOWED_ORIGIN_BROWSER_LOCALHOST APIM_ALLOWED_ORIGIN_OPERATOR_CONSOLE APIM_ALLOWED_ORIGIN_VITE APIM_ALLOWED_ORIGIN_GATEWAY \
    APIM_EDGE_ROOT_HOST APIM_EDGE_HOST APIM_EDGE_WILDCARD_HOST \
    SMOKE_HELLO_BASE_URL SMOKE_HELLO_KEYCLOAK_BASE_URL SMOKE_OIDC_BASE_URL SMOKE_OIDC_KEYCLOAK_BASE_URL EDGE_HTTP_BASE_URL EDGE_TLS_BASE_URL
  do
    printf 'export %s=%q\n' "$name" "${!name-}"
  done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  set -euo pipefail
  stack_env_init
  stack_env_print_exports
fi
