apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubernetes-provider-demo
  namespace: eso-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-demo-store
    kind: SecretStore
  target:
    name: eso-demo-materialized
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: eso-demo-source
        property: api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
