apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-secret-store
  namespace: eso-demo
spec:
  provider:
    fake:
      data:
        - key: demo/api-key
          value: local-fake-provider-api-key
