#!/usr/bin/env bats
#
# Pure-function coverage for dependency version resolution and the
# verifiability gate. No cluster, no network, no Docker: this is the subset
# that must also pass on macOS, where the stock awk is BSD rather than gawk and
# the stock bash is 3.2.

setup() {
  export REPO_ROOT
  REPO_ROOT="$(cd "$(dirname "${BATS_TEST_FILENAME}")/../../.." && pwd)"
  export SCRIPT="${REPO_ROOT}/terraform/kubernetes/scripts/check-component-version.sh"
}

@test "check-version reads resolved versions from a Yarn Berry lockfile" {
  local yarn_fixture="${BATS_TEST_TMPDIR}/yarn-app"
  mkdir -p "${yarn_fixture}"
  cat >"${yarn_fixture}/yarn.lock" <<'EOF'
# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@scope/pkg@npm:^1.2.0":
  version: 1.2.3
  resolution: "@scope/pkg@npm:1.2.3"
  languageName: node
  linkType: hard

"multi@npm:^0.9.28, multi@npm:^0.9.31":
  version: 0.9.31
  resolution: "multi@npm:0.9.31"
  languageName: node
  linkType: hard

"prefix-collide@npm:^2.0.0":
  version: 2.0.0
  resolution: "prefix-collide@npm:2.0.0"
  languageName: node
  linkType: hard
EOF

  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; printf '%s\n' \
    \"\$(yarn_lock_resolved_version '${yarn_fixture}/yarn.lock' '@scope/pkg')\" \
    \"\$(yarn_lock_resolved_version '${yarn_fixture}/yarn.lock' 'multi')\" \
    \"\$(yarn_lock_resolved_version '${yarn_fixture}/yarn.lock' 'prefix')\" \
    \"\$(yarn_lock_resolved_version '${yarn_fixture}/yarn.lock' 'absent')\""

  [ "${status}" -eq 0 ]
  # "prefix" must not match the "prefix-collide" entry.
  [ "${output}" = "$(printf '1.2.3\n0.9.31\n\n')" ]
}

@test "check-version resolves workspace member deps from the root lockfile" {
  local root="${BATS_TEST_TMPDIR}/ws"
  mkdir -p "${root}/packages/app"
  cat >"${root}/yarn.lock" <<'EOF'
__metadata:
  version: 8

"@scope/pkg@npm:^1.2.0":
  version: 1.2.3
  resolution: "@scope/pkg@npm:1.2.3"
  languageName: node
  linkType: hard
EOF

  # The workspace member has a package.json but no lockfile of its own, which
  # is what left the Backstage tree reported as lockfile_missing_or_unverified.
  # REPO_ROOT is overridden after sourcing: the script loads libraries relative
  # to it at load time.
  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; REPO_ROOT='${root}'; printf '%s\n' \
    \"\$(js_lock_resolved_version '${root}/packages/app' '@scope/pkg')\" \
    \"\$(js_lock_resolved_version '${root}/packages/app' 'absent')\""

  [ "${status}" -eq 0 ]
  [ "${output}" = "$(printf '1.2.3\n')" ]
}

@test "check-version lockfile lookup does not escape the repository root" {
  local outside="${BATS_TEST_TMPDIR}/outside"
  local root="${outside}/repo"
  mkdir -p "${root}/app"
  cat >"${outside}/yarn.lock" <<'EOF'
__metadata:
  version: 8

"@scope/pkg@npm:^1.2.0":
  version: 9.9.9
  resolution: "@scope/pkg@npm:9.9.9"
  languageName: node
  linkType: hard
EOF

  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; REPO_ROOT='${root}'; \
    js_lock_resolved_version '${root}/app' '@scope/pkg'"

  [ "${status}" -eq 0 ]
  [ -z "${output}" ]
}

@test "check-version flags rows whose version could not be verified" {
  # Row format is app, dependency, current, latest_eligible, latest_overall, status.
  local rows
  rows="$(printf 'apps/a\tgood\t1.0.0\t1.1.0\t1.1.0\tcurrent\napps/a\tbad\t\t\t\tlockfile missing or unverified\napps/a\tflaky\t1.0.0\t\t\tlatest lookup failed\n')"

  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; unverifiable_dependency_rows \"\$(printf 'apps/a\tgood\t1.0.0\t1.1.0\t1.1.0\tcurrent\napps/a\tbad\t\t\t\tlockfile missing or unverified\napps/a\tflaky\t1.0.0\t\t\tlatest lookup failed\n')\" 0"

  [ "${status}" -eq 0 ]
  [[ "${output}" == *"bad"* ]]
  [[ "${output}" == *"flaky"* ]]
  [[ "${output}" != *"good"* ]]
}

@test "check-version can tolerate transient lookup failures but never a missing lockfile" {
  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; unverifiable_dependency_rows \"\$(printf 'apps/a\tbad\t\t\t\tlockfile missing or unverified\napps/a\tflaky\t1.0.0\t\t\tlatest lookup failed\n')\" 1"

  [ "${status}" -eq 0 ]
  [[ "${output}" == *"bad"* ]]
  [[ "${output}" != *"flaky"* ]]
}

@test "check-version reports nothing unverifiable for a fully resolved set" {
  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; unverifiable_dependency_rows \"\$(printf 'apps/a\tgood\t1.0.0\t1.1.0\t1.1.0\tcurrent\napps/a\tcool\t1.0.0\t1.0.0\t1.1.0\tcooldown active\n')\" 0"

  [ "${status}" -eq 0 ]
  [ -z "${output}" ]
}

@test "check-version strict mode exits non-zero when a dependency is unverifiable" {
  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; assert_dependencies_verifiable \"\$(printf 'apps/a\tbad\t\t\t\tlockfile missing or unverified\n')\" 0"

  [ "${status}" -ne 0 ]
  [[ "${output}" == *"bad"* ]]
  [[ "${output}" == *"unverifiable"* ]]
}

@test "check-version strict mode passes when everything resolved" {
  run bash -lc "export CHECK_VERSION_LIB_ONLY=1; source '${SCRIPT}'; assert_dependencies_verifiable \"\$(printf 'apps/a\tgood\t1.0.0\t1.1.0\t1.1.0\tcurrent\n')\" 0"

  [ "${status}" -eq 0 ]
}
