#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
# shellcheck source=/dev/null
source "${REPO_ROOT}/scripts/lib/shell-cli.sh"

fail() {
  echo "render-operator-overrides: $*" >&2
  exit 1
}

quote_hcl() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

mode="${KIND_IMAGE_DISTRIBUTION_MODE:-load}"
worker_count="${KIND_WORKER_COUNT:-1}"
cache_host="${KIND_LOCAL_IMAGE_CACHE_HOST:-host.docker.internal:5002}"
baked_node_image="${KIND_BAKED_NODE_IMAGE:-}"
backstage_mode="${KIND_ENABLE_BACKSTAGE:-auto}"
backstage_min_docker_memory_bytes="${KIND_BACKSTAGE_MIN_DOCKER_MEMORY_BYTES:-10737418240}"
output_file="${KIND_OPERATOR_OVERRIDES_FILE:-}"

usage() {
  cat <<EOF
Usage: ${0##*/} [--dry-run] [--execute]

Renders the kind operator override tfvars fragment from the current image
distribution environment variables.

$(shell_cli_standard_options)
EOF
}

shell_cli_handle_standard_no_args usage "would render kind operator overrides into the configured output file" "$@"

[ -n "${output_file}" ] || fail "KIND_OPERATOR_OVERRIDES_FILE is required"

case "${mode}" in
  load|registry|hybrid|baked) ;;
  *) fail "invalid KIND_IMAGE_DISTRIBUTION_MODE=${mode} (expected load|registry|hybrid|baked)" ;;
esac

case "${backstage_mode}" in
  auto|on|off) ;;
  *) fail "invalid KIND_ENABLE_BACKSTAGE=${backstage_mode} (expected auto|on|off)" ;;
esac

[[ "${worker_count}" =~ ^[0-9]+$ ]] || fail "KIND_WORKER_COUNT must be a whole number"
if (( worker_count < 1 )); then
  fail "KIND_WORKER_COUNT must be at least 1 (1 worker = 2 total nodes)"
fi
[[ "${backstage_min_docker_memory_bytes}" =~ ^[0-9]+$ ]] || fail "KIND_BACKSTAGE_MIN_DOCKER_MEMORY_BYTES must be a whole number"

detect_docker_memory_bytes() {
  command -v docker >/dev/null 2>&1 || return 0
  docker info --format '{{json .MemTotal}}' 2>/dev/null | tr -d '"'
}

source_fingerprint_tag() {
  local digest

  digest="$(
    cd "${REPO_ROOT}"
    find "$@" -type f -print |
      LC_ALL=C sort |
      while IFS= read -r source_file; do
        printf '%s\n' "${source_file}"
        shasum -a 256 "${source_file}"
      done |
      shasum -a 256 |
      awk '{print $1}'
  )"
  printf 'src-%s' "${digest:0:20}"
}

backstage_enabled="false"
backstage_detected_memory=""
case "${backstage_mode}" in
  on)
    backstage_enabled="true"
    ;;
  off)
    backstage_enabled="false"
    ;;
  auto)
    backstage_detected_memory="$(detect_docker_memory_bytes || true)"
    if [[ "${backstage_detected_memory}" =~ ^[0-9]+$ ]] && (( backstage_detected_memory >= backstage_min_docker_memory_bytes )); then
      backstage_enabled="true"
    fi
    ;;
esac

case "${mode}" in
  baked|hybrid)
    [ -n "${baked_node_image}" ] || fail "KIND_BAKED_NODE_IMAGE is required when KIND_IMAGE_DISTRIBUTION_MODE=${mode}"
    ;;
esac

mkdir -p "$(dirname "${output_file}")"

platform_mcp_image_tag="$(
  source_fingerprint_tag \
    apps/platform-mcp/.dockerignore \
    apps/platform-mcp/Dockerfile \
    apps/platform-mcp/Dockerfile.dockerignore \
    apps/platform-mcp/platform_mcp \
    apps/platform-mcp/pyproject.toml \
    apps/platform-mcp/uv.lock
)"
idp_core_image_tag="$(
  source_fingerprint_tag \
    apps/idp-core/.dockerignore \
    apps/idp-core/Dockerfile \
    apps/idp-core/Dockerfile.dockerignore \
    apps/idp-core/app \
    apps/idp-core/pyproject.toml \
    apps/idp-core/uv.lock \
    catalog/platform-apps.json
)"
backstage_image_tag="$(
  if [ "${backstage_enabled}" = "true" ]; then
    source_fingerprint_tag \
      apps/subnetcalc/catalog-info.yaml \
      apps/subnetcalc/docs \
      apps/subnetcalc/mkdocs.yml \
      apps/subnetcalc/README.md \
      apps/apim-simulator/catalog-info.yaml \
      apps/sentiment/catalog-info.yaml \
      apps/sentiment/docs \
      apps/sentiment/mkdocs.yml \
      apps/sentiment/MODEL_CARD.md \
      apps/sentiment/README.md \
      apps/backstage/.dockerignore \
      apps/backstage/.yarnrc.yml \
      apps/backstage/.yarn \
      apps/backstage/Dockerfile \
      apps/backstage/app-config.production.yaml \
      apps/backstage/app-config.yaml \
      apps/backstage/backstage.json \
      apps/backstage/catalog \
      apps/backstage/catalog-info.yaml \
      apps/backstage/package.json \
      apps/backstage/packages \
      apps/backstage/plugins \
      apps/backstage/tsconfig.json \
      apps/backstage/yarn.lock
  fi
)"

write_external_platform_images() {
  cat <<EOF
prefer_external_platform_images = true
external_platform_image_refs = {
  backstage = $(quote_hcl "${cache_host}/platform/backstage:${backstage_image_tag:-latest}")
  grafana    = $(quote_hcl "${cache_host}/platform/grafana-victorialogs:latest")
  "idp-core" = $(quote_hcl "${cache_host}/platform/idp-core:${idp_core_image_tag}")
}
EOF
}

{
  echo "# Generated by kubernetes/kind/scripts/render-operator-overrides.sh"
  echo "# KIND_WORKER_COUNT counts worker nodes. Total kind nodes = workers + 1 control-plane."
  echo "worker_count = ${worker_count}"
  if [ "${backstage_mode}" = "auto" ]; then
    echo "# KIND_ENABLE_BACKSTAGE=auto, Docker MemTotal=${backstage_detected_memory:-unknown}, minimum=${backstage_min_docker_memory_bytes}"
  else
    echo "# KIND_ENABLE_BACKSTAGE=${backstage_mode}"
  fi
  echo "enable_backstage = ${backstage_enabled}"

  case "${mode}" in
    load)
      ;;
    registry)
      cat <<EOF
enable_image_preload = false
enable_apps_dir_mount = false
enable_docker_socket_mount = false
enable_actions_runner = false
$(write_external_platform_images)
prefer_external_workload_images = true
external_workload_image_refs = {
  sentiment-api                        = $(quote_hcl "${cache_host}/platform/sentiment-api:latest")
  sentiment-auth-ui                    = $(quote_hcl "${cache_host}/platform/sentiment-auth-ui:latest")
  subnetcalc-api-fastapi-container-app = $(quote_hcl "${cache_host}/platform/subnetcalc-api-fastapi-container-app:latest")
  subnetcalc-apim-simulator            = $(quote_hcl "${cache_host}/platform/subnetcalc-apim-simulator:latest")
  platform-mcp                         = $(quote_hcl "${cache_host}/platform/platform-mcp:${platform_mcp_image_tag}")
  subnetcalc-frontend-react            = $(quote_hcl "${cache_host}/platform/subnetcalc-frontend-react:latest")
  subnetcalc-frontend-typescript-vite  = $(quote_hcl "${cache_host}/platform/subnetcalc-frontend-typescript-vite:latest")
}
EOF
      ;;
    baked)
      echo "enable_image_preload = false"
      echo "node_image = $(quote_hcl "${baked_node_image}")"
      ;;
    hybrid)
      cat <<EOF
enable_image_preload = false
enable_apps_dir_mount = false
enable_docker_socket_mount = false
enable_actions_runner = false
$(write_external_platform_images)
prefer_external_workload_images = true
node_image = $(quote_hcl "${baked_node_image}")
external_workload_image_refs = {
  sentiment-api                        = $(quote_hcl "${cache_host}/platform/sentiment-api:latest")
  sentiment-auth-ui                    = $(quote_hcl "${cache_host}/platform/sentiment-auth-ui:latest")
  subnetcalc-api-fastapi-container-app = $(quote_hcl "${cache_host}/platform/subnetcalc-api-fastapi-container-app:latest")
  subnetcalc-apim-simulator            = $(quote_hcl "${cache_host}/platform/subnetcalc-apim-simulator:latest")
  platform-mcp                         = $(quote_hcl "${cache_host}/platform/platform-mcp:${platform_mcp_image_tag}")
  subnetcalc-frontend-react            = $(quote_hcl "${cache_host}/platform/subnetcalc-frontend-react:latest")
  subnetcalc-frontend-typescript-vite  = $(quote_hcl "${cache_host}/platform/subnetcalc-frontend-typescript-vite:latest")
}
EOF
      ;;
  esac
} > "${output_file}"

printf '%s\n' "${output_file}"
