apiVersion: v1
kind: Pod
metadata:
  name: hardened-platform-pod
  namespace: idp
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: quay.io/cilium/cilium:v1.19.1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      resources:
        limits:
          memory: 64Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: soft-platform-pod
  namespace: idp
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: quay.io/cilium/cilium:v1.19.1
      resources:
        limits:
          memory: 64Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-platform-pod
  namespace: idp
spec:
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: quay.io/cilium/cilium:v1.19.1
      securityContext:
        privileged: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      resources:
        limits:
          memory: 64Mi
