apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}-backend
  labels:
    app.kubernetes.io/name: ${{ values.name }}-backend
    app.kubernetes.io/component: backend
    app: ${{ values.name }}
    project: kindlocal
    team: ${{ values.team }}
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.name }}-backend
      app.kubernetes.io/component: backend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "${{ values.backendPort }}"
      labels:
        app.kubernetes.io/name: ${{ values.name }}-backend
        app.kubernetes.io/component: backend
        app: ${{ values.name }}
        project: kindlocal
        team: ${{ values.team }}
        tier: backend
    spec:
      imagePullSecrets:
        - name: gitea-registry-creds
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: localhost:30090/platform/${{ values.name }}-backend:latest
          imagePullPolicy: Always
          env:
            - name: OTEL_SERVICE_NAME
              value: ${{ values.name }}-backend
            - name: OTEL_SERVICE_NAMESPACE
              value: ${{ values.team }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=0.1.0,k8s.deployment.name=${{ values.name }}-backend
            - name: LOG_FORMAT
              value: json
          ports:
            - name: http
              containerPort: ${{ values.backendPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}-backend
  labels:
    app.kubernetes.io/name: ${{ values.name }}-backend
    app.kubernetes.io/component: backend
    app: ${{ values.name }}
    project: kindlocal
    team: ${{ values.team }}
    tier: backend
spec:
  selector:
    app.kubernetes.io/name: ${{ values.name }}-backend
    app.kubernetes.io/component: backend
  ports:
    - name: http
      appProtocol: http
      port: ${{ values.backendPort }}
      targetPort: http
