#!/bin/sh
set -eu

OUT_FILE="${RUNTIME_CONFIG_OUT:-/usr/share/nginx/html/runtime-config.js}"

mkdir -p "$(dirname "$OUT_FILE")"

js_escape() {
  printf '%s' "$1" | awk '
    BEGIN { ORS="" }
    {
      gsub(/\\/,"\\\\")
      gsub(/"/,"\\\"")
      gsub(/\r/,"\\r")
      gsub(/\t/,"\\t")
      if (NR > 1) {
        printf "\\n"
      }
      printf "%s", $0
    }
  '
}

runtime_value() {
  value="$1"
  escaped="$(js_escape "$value")"
  printf '"%s"' "$escaped"
}

AUTH_METHOD_VALUE="${AUTH_METHOD:-${AUTH_MODE:-${VITE_AUTH_METHOD:-none}}}"
AUTH_ENABLED_VALUE="${AUTH_ENABLED:-${VITE_AUTH_ENABLED:-}}"
if [ -z "${AUTH_ENABLED_VALUE}" ]; then
  case "${AUTH_METHOD_VALUE}" in
    ""|none)
      AUTH_ENABLED_VALUE="false"
      ;;
    *)
      AUTH_ENABLED_VALUE="true"
      ;;
  esac
fi

API_BASE_URL_VALUE="${API_BASE_URL:-${VITE_API_BASE_URL:-${VITE_API_URL:-}}}"
API_PROXY_ENABLED_VALUE="${API_PROXY_ENABLED:-${VITE_API_PROXY_ENABLED:-false}}"
JWT_USERNAME_VALUE="${JWT_USERNAME:-${VITE_JWT_USERNAME:-}}"
JWT_PASSWORD_VALUE="${JWT_PASSWORD:-${VITE_JWT_PASSWORD:-}}"
AZURE_CLIENT_ID_VALUE="${AZURE_CLIENT_ID:-${VITE_AZURE_CLIENT_ID:-}}"
AZURE_TENANT_ID_VALUE="${AZURE_TENANT_ID:-${VITE_AZURE_TENANT_ID:-common}}"
AZURE_REDIRECT_URI_VALUE="${AZURE_REDIRECT_URI:-${VITE_AZURE_REDIRECT_URI:-}}"
EASYAUTH_RESOURCE_ID_VALUE="${EASYAUTH_RESOURCE_ID:-${VITE_EASYAUTH_RESOURCE_ID:-}}"
OIDC_AUTHORITY_VALUE="${OIDC_AUTHORITY:-${VITE_OIDC_AUTHORITY:-}}"
OIDC_CLIENT_ID_VALUE="${OIDC_CLIENT_ID:-${VITE_OIDC_CLIENT_ID:-}}"
OIDC_REDIRECT_URI_VALUE="${OIDC_REDIRECT_URI:-${VITE_OIDC_REDIRECT_URI:-}}"
OIDC_AUTO_LOGIN_VALUE="${OIDC_AUTO_LOGIN:-${VITE_OIDC_AUTO_LOGIN:-false}}"
OIDC_PROMPT_VALUE="${OIDC_PROMPT:-${VITE_OIDC_PROMPT:-}}"
OIDC_FORCE_REAUTH_VALUE="${OIDC_FORCE_REAUTH:-${VITE_OIDC_FORCE_REAUTH:-false}}"
APIM_SUBSCRIPTION_KEY_VALUE="${APIM_SUBSCRIPTION_KEY:-${VITE_APIM_SUBSCRIPTION_KEY:-}}"
SHOW_NETWORK_PATH_VALUE="${SHOW_NETWORK_PATH:-${VITE_SHOW_NETWORK_PATH:-false}}"
NETWORK_HOPS_VALUE="${NETWORK_HOPS:-${VITE_NETWORK_HOPS:-}}"
NETWORK_DIAGNOSTICS_LABEL_VALUE="${NETWORK_DIAGNOSTICS_LABEL:-${VITE_NETWORK_DIAGNOSTICS_LABEL:-}}"
SECONDARY_NETWORK_DIAGNOSTICS_LABEL_VALUE="${SECONDARY_NETWORK_DIAGNOSTICS_LABEL:-${VITE_SECONDARY_NETWORK_DIAGNOSTICS_LABEL:-}}"
SECONDARY_NETWORK_DIAGNOSTICS_PATH_VALUE="${SECONDARY_NETWORK_DIAGNOSTICS_PATH:-${VITE_SECONDARY_NETWORK_DIAGNOSTICS_PATH:-}}"
FRONTEND_STATUS_LABEL_VALUE="${FRONTEND_STATUS_LABEL:-${VITE_FRONTEND_STATUS_LABEL:-}}"
API_INGRESS_STATUS_LABEL_VALUE="${API_INGRESS_STATUS_LABEL:-${VITE_API_INGRESS_STATUS_LABEL:-}}"
BACKEND_PATH_STATUS_LABEL_VALUE="${BACKEND_PATH_STATUS_LABEL:-${VITE_BACKEND_PATH_STATUS_LABEL:-}}"
BACKEND_PATH_STATUS_DETAIL_VALUE="${BACKEND_PATH_STATUS_DETAIL:-${VITE_BACKEND_PATH_STATUS_DETAIL:-}}"

cat >"${OUT_FILE}" <<EOF
window.RUNTIME_CONFIG = Object.assign({}, window.RUNTIME_CONFIG || {}, {
  API_BASE_URL: $(runtime_value "${API_BASE_URL_VALUE}"),
  API_PROXY_ENABLED: $(runtime_value "${API_PROXY_ENABLED_VALUE}"),
  AUTH_METHOD: $(runtime_value "${AUTH_METHOD_VALUE}"),
  AUTH_ENABLED: $(runtime_value "${AUTH_ENABLED_VALUE}"),
  JWT_USERNAME: $(runtime_value "${JWT_USERNAME_VALUE}"),
  JWT_PASSWORD: $(runtime_value "${JWT_PASSWORD_VALUE}"),
  AZURE_CLIENT_ID: $(runtime_value "${AZURE_CLIENT_ID_VALUE}"),
  AZURE_TENANT_ID: $(runtime_value "${AZURE_TENANT_ID_VALUE}"),
  AZURE_REDIRECT_URI: $(runtime_value "${AZURE_REDIRECT_URI_VALUE}"),
  EASYAUTH_RESOURCE_ID: $(runtime_value "${EASYAUTH_RESOURCE_ID_VALUE}"),
  OIDC_AUTHORITY: $(runtime_value "${OIDC_AUTHORITY_VALUE}"),
  OIDC_CLIENT_ID: $(runtime_value "${OIDC_CLIENT_ID_VALUE}"),
  OIDC_REDIRECT_URI: $(runtime_value "${OIDC_REDIRECT_URI_VALUE}"),
  OIDC_AUTO_LOGIN: $(runtime_value "${OIDC_AUTO_LOGIN_VALUE}"),
  OIDC_PROMPT: $(runtime_value "${OIDC_PROMPT_VALUE}"),
  OIDC_FORCE_REAUTH: $(runtime_value "${OIDC_FORCE_REAUTH_VALUE}"),
  APIM_SUBSCRIPTION_KEY: $(runtime_value "${APIM_SUBSCRIPTION_KEY_VALUE}"),
  SHOW_NETWORK_PATH: $(runtime_value "${SHOW_NETWORK_PATH_VALUE}"),
  NETWORK_HOPS: $(runtime_value "${NETWORK_HOPS_VALUE}"),
  NETWORK_DIAGNOSTICS_LABEL: $(runtime_value "${NETWORK_DIAGNOSTICS_LABEL_VALUE}"),
  SECONDARY_NETWORK_DIAGNOSTICS_LABEL: $(runtime_value "${SECONDARY_NETWORK_DIAGNOSTICS_LABEL_VALUE}"),
  SECONDARY_NETWORK_DIAGNOSTICS_PATH: $(runtime_value "${SECONDARY_NETWORK_DIAGNOSTICS_PATH_VALUE}"),
  FRONTEND_STATUS_LABEL: $(runtime_value "${FRONTEND_STATUS_LABEL_VALUE}"),
  API_INGRESS_STATUS_LABEL: $(runtime_value "${API_INGRESS_STATUS_LABEL_VALUE}"),
  BACKEND_PATH_STATUS_LABEL: $(runtime_value "${BACKEND_PATH_STATUS_LABEL_VALUE}"),
  BACKEND_PATH_STATUS_DETAIL: $(runtime_value "${BACKEND_PATH_STATUS_DETAIL_VALUE}")
});
EOF
