name: build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  images:
    runs-on: [self-hosted, in-cluster]
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Build backend image
        run: docker build -t localhost:30090/platform/${{ values.name }}-backend:latest apps/backend
      - name: Build frontend image
        run: docker build -t localhost:30090/platform/${{ values.name }}-frontend:latest apps/frontend
