@base = http://localhost:8000
@tenant = local-dev-tenant-key

GET {{base}}/apim/management/apis
X-Apim-Tenant-Key: {{tenant}}

###

PUT {{base}}/apim/management/policies/api/tutorial-api
X-Apim-Tenant-Key: {{tenant}}
Content-Type: application/json

{
  "xml": "<policies><inbound /><backend /><outbound><set-header name=\"x-from-vscode\" exists-action=\"override\"><value>true</value></set-header></outbound><on-error /></policies>"
}
