apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-gateway-tls
  namespace: platform-gateway
spec:
  secretName: platform-gateway-tls
  issuerRef:
    name: mkcert-ca
    kind: ClusterIssuer
  dnsNames:
    - '*.127.0.0.1.sslip.io'
    - '*.admin.127.0.0.1.sslip.io'
    - '*.dev.127.0.0.1.sslip.io'
    - '*.uat.127.0.0.1.sslip.io'
    - argocd.admin.127.0.0.1.sslip.io
    - gitea.admin.127.0.0.1.sslip.io
    - hubble.admin.127.0.0.1.sslip.io
    - signoz.admin.127.0.0.1.sslip.io
    - sentiment.dev.127.0.0.1.sslip.io
    - sentiment.uat.127.0.0.1.sslip.io
    - subnetcalc.dev.127.0.0.1.sslip.io
    - subnetcalc.uat.127.0.0.1.sslip.io
