apiVersion: v1
kind: Service
metadata:
  name: llm-gateway
  labels:
    app.kubernetes.io/name: llm-gateway
    app.kubernetes.io/component: llm
    app: sentiment
    project: kindlocal
    team: dolphin
    tier: backend
    role: llm
spec:
  type: ExternalName
  externalName: __LLM_GATEWAY_EXTERNAL_NAME__
