apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api
spec:
  template:
    spec:
      containers:
        - name: api
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-auth-ui
spec:
  template:
    spec:
      containers:
        - name: ui
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-router
spec:
  template:
    spec:
      containers:
        - name: nginx
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnetcalc-api
spec:
  template:
    spec:
      containers:
        - name: api
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnetcalc-frontend
spec:
  template:
    spec:
      containers:
        - name: ui
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnetcalc-router
spec:
  template:
    spec:
      containers:
        - name: nginx
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
