apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - snippetsfilter-admin-allowlist.yaml
  - httproute-argocd.yaml
  - httproute-gitea.yaml
  - httproute-headlamp.yaml
  - httproute-hubble.yaml
  - httproute-agentgateway-ai-gateway.yaml
  - httproute-kyverno.yaml
  - httproute-subnetcalc-frontend-dev.yaml
  - referencegrant-argocd.yaml
  - referencegrant-gitea.yaml
  - referencegrant-headlamp.yaml
  - referencegrant-hubble.yaml
  - referencegrant-dev-subnetcalc-frontend.yaml
  - referencegrant-agentgateway-ai-gateway.yaml
  - referencegrant-policy-reporter.yaml
