apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-routes-subnetcalc-frontend
  namespace: dev
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gateway-routes
  to:
    - group: ""
      kind: Service
      name: subnetcalc-frontend
    - group: ""
      kind: Service
      name: subnetcalc-frontend-canary
