apiVersion: v1
kind: Namespace
metadata:
  name: gateway-routes
  labels:
    app.kubernetes.io/name: gateway-routes
    app.kubernetes.io/managed-by: argocd
    platform-gateway-access: "true"
    "platform.publiccloudexperiments.net/namespace-role": shared
