apiVersion: gateway.nginx.org/v1alpha2
kind: ObservabilityPolicy
metadata:
  name: tracing
  namespace: gateway-routes
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: argocd
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gitea
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hubble
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: dex
  tracing:
    context: propagate
    ratio: 100
    strategy: ratio
