apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-routes-langfuse-demos
  namespace: sso
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gateway-routes
  to:
    - group: ""
      kind: Service
      name: oauth2-proxy-langfuse-trace-chat
    - group: ""
      kind: Service
      name: oauth2-proxy-langfuse-tool-agent
    - group: ""
      kind: Service
      name: oauth2-proxy-langfuse-eval-runner
