apiVersion: v1
kind: ServiceAccount
metadata:
  name: act-runner
  namespace: gitea-runner
  labels:
    app.kubernetes.io/name: act-runner
    app.kubernetes.io/part-of: gitea
automountServiceAccountToken: true
