#!/usr/bin/env bash

DEVCONTAINER_DOCKER_FEATURE_REF="${DEVCONTAINER_DOCKER_FEATURE_REF:-ghcr.io/devcontainers/features/docker-outside-of-docker:1.9.1}"
DEVCONTAINER_DOCKER_CLI_VERSION="${DEVCONTAINER_DOCKER_CLI_VERSION:-29.4.1}"
DEVCONTAINER_DOCKER_BUILDX_VERSION="${DEVCONTAINER_DOCKER_BUILDX_VERSION:-0.33.0}"
DEVCONTAINER_DOCKER_COMPOSE_CHANNEL="${DEVCONTAINER_DOCKER_COMPOSE_CHANNEL:-v2}"
DEVCONTAINER_NODE_FEATURE_REF="${DEVCONTAINER_NODE_FEATURE_REF:-ghcr.io/devcontainers/features/node:1.7.1}"
DEVCONTAINER_NODE_VERSION="${DEVCONTAINER_NODE_VERSION:-24.15.0}"
DEVCONTAINER_NODE_PNPM_VERSION="${DEVCONTAINER_NODE_PNPM_VERSION:-none}"
DEVCONTAINER_NODE_NVM_VERSION="${DEVCONTAINER_NODE_NVM_VERSION:-0.40.4}"

ARKADE_VERSION="${ARKADE_VERSION:-0.11.93}"
BUN_VERSION="${BUN_VERSION:-bun-v1.3.14}"
KYVERNO_VERSION="${KYVERNO_VERSION:-v1.18.1}"
LEFTHOOK_VERSION="${LEFTHOOK_VERSION:-v2.1.9}"
LIMA_VERSION="${LIMA_VERSION:-v2.1.1}"
MKCERT_VERSION="${MKCERT_VERSION:-v1.4.4}"
OPENTOFU_VERSION="${OPENTOFU_VERSION:-1.12.3}"
STARSHIP_VERSION="${STARSHIP_VERSION:-v1.26.0}"
STEP_VERSION="${STEP_VERSION:-v0.30.6}"
VIM_SENSIBLE_REF="${VIM_SENSIBLE_REF:-0ce2d843d6f588bb0c8c7eec6449171615dc56d9}"

# shellcheck disable=SC2034 # sourced by install/check scripts that consume the version matrix
DEVCONTAINER_ARKADE_TOOLS=(
  "cilium=v0.19.5"
  "helm=v4.2.2"
  "hubble=v1.19.4"
  "jq=jq-1.8.2"
  "k3sup=0.13.12"
  "kind=v0.32.0"
  "kubectl=v1.36.2"
  "kubie=v0.28.0"
  "kubectx=v0.11.0"
  "terragrunt=v1.1.0"
  "yq=v4.53.3"
)
