pid /tmp/nginx.pid;

events {}

http {
  access_log /dev/stdout;
  error_log /dev/stderr warn;

  server {
    listen ${{ values.frontendPort }};
    root /usr/share/nginx/html;

    location / {
      try_files $uri /index.html;
    }

    location /api/ {
      proxy_pass http://${{ values.name }}-backend:${{ values.backendPort }}/;
    }
  }
}

