apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sentiment-router-ingress
spec:
  description: >-
    Allow only shared auth proxies to reach the sentiment router.
  endpointSelector:
    matchLabels:
      "k8s:project": kindlocal
      "k8s:team": dolphin
      "k8s:app": sentiment
      "k8s:tier": gateway
      "k8s:app.kubernetes.io/name": sentiment-router
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.cilium.k8s.namespace.labels.platform.publiccloudexperiments.net/namespace-role": shared
            "k8s:app.kubernetes.io/component": authentication-proxy
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sentiment-backend-ingress
spec:
  description: >-
    Allow only the sentiment router to reach the sentiment API.
  endpointSelector:
    matchLabels:
      "k8s:project": kindlocal
      "k8s:team": dolphin
      "k8s:app": sentiment
      "k8s:tier": backend
      "k8s:app.kubernetes.io/name": sentiment-api
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:project": kindlocal
            "k8s:team": dolphin
            "k8s:app": sentiment
            "k8s:tier": gateway
            "k8s:app.kubernetes.io/name": sentiment-router
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sentiment-frontend-ingress
spec:
  description: >-
    Allow only the sentiment router to reach the sentiment frontend.
  endpointSelector:
    matchLabels:
      "k8s:project": kindlocal
      "k8s:team": dolphin
      "k8s:app": sentiment
      "k8s:tier": frontend
      "k8s:app.kubernetes.io/name": sentiment-auth-ui
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:project": kindlocal
            "k8s:team": dolphin
            "k8s:app": sentiment
            "k8s:tier": gateway
            "k8s:app.kubernetes.io/name": sentiment-router
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sentiment-api-egress
spec:
  description: >-
    Allow the sentiment API to emit OTEL data.
  endpointSelector:
    matchLabels:
      "k8s:project": kindlocal
      "k8s:team": dolphin
      "k8s:app": sentiment
      "k8s:tier": backend
      "k8s:app.kubernetes.io/name": sentiment-api
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": observability
            "k8s:app.kubernetes.io/name": otel-collector
      toPorts:
        - ports:
            - port: "4317"
              protocol: TCP
            - port: "4318"
              protocol: TCP
