services:
  hello-api:
    environment:
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_DEPLOYMENT_ENVIRONMENT: local
      OTEL_SERVICE_NAMESPACE: apim-simulator.examples
    depends_on:
      lgtm:
        condition: service_started
