#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=/dev/null
source "${REPO_ROOT}/scripts/lib/shell-cli.sh"

OUTPUT_FORMAT="text"
TARGET="kind"
STAGE="700"
ACTION="plan"
AUTO_APPROVE="0"
TFVARS_FILE=""
PROFILE_NAME=""
PROFILE_PATH=""
SAVE_PROFILE_NAME=""
PROFILES_DIR=""
APP_SENTIMENT=""
APP_SUBNETCALC=""

usage() {
  cat <<'EOF' | sed "1s|@SCRIPT_NAME@|${0##*/}|"
Usage: @SCRIPT_NAME@ <options|preview|apply|save-profile> [options] [--dry-run] [--execute]

Builds a stable platform workflow command from operator intent. The workflow
core is non-interactive so the TUI, future web UI, and scripts can share the
same contract.

Subcommands:
  options   List supported targets, stages, actions, and app toggles
  preview   Render the generated tfvars fragment and make command
  apply     Render the generated tfvars fragment and execute the make command
  save-profile
            Persist generated tfvars as a named target profile

Workflow options:
  --target kind|lima|slicer       Kubernetes target stack (default: kind)
  --stage 100|200|...|900|950-local-idp
                                  Cumulative stage or named stage-like target (default: 700)
  --action plan|apply|status|show-urls|check-health|check-security|check-rbac
                                  Make workflow action (default: plan)
  --profile-name NAME             Name for save-profile output
  --profiles-dir PATH             Directory for save-profile output
  --app sentiment=on|off          Override sentiment app repo/workload toggle
  --app subnetcalc=on|off         Override subnetcalc app repo/workload toggle
  --tfvars-file PATH              Generated tfvars path (default: .run/operator/<target>-stage<stage>.tfvars)
  --auto-approve                  Add AUTO_APPROVE=1 for apply/reset-capable workflows
  --output text|json              Output format (default: text)
EOF
  printf '\n%s\n' "$(shell_cli_standard_options)"
}

die_usage() {
  printf '%s\n' "$*" >&2
  exit 2
}

require_value() {
  local flag="$1"
  local value="${2-}"

  if [[ -z "${value}" ]]; then
    shell_cli_missing_value "$(shell_cli_script_name)" "${flag}"
    exit 2
  fi
}

target_path() {
  case "$1" in
    kind) printf 'kubernetes/kind' ;;
    lima) printf 'kubernetes/lima' ;;
    slicer) printf 'kubernetes/slicer' ;;
    *) return 1 ;;
  esac
}

validate_target() {
  target_path "$1" >/dev/null || die_usage "Invalid --target '${1}'. Expected one of: kind, lima, slicer"
}

validate_stage() {
  case "${TARGET}:$1" in
    *:100|*:200|*:300|*:400|*:500|*:600|*:700|*:800|*:900|kind:950-local-idp) ;;
    *:950-local-idp) die_usage "Stage '950-local-idp' is only available for target kind" ;;
    *) die_usage "Invalid --stage '${1}'. Expected one of: 100, 200, 300, 400, 500, 600, 700, 800, 900$(if [[ "${TARGET}" = "kind" ]]; then printf ', 950-local-idp'; fi)" ;;
  esac
}

validate_action() {
  case "$1" in
    plan|apply|status|show-urls|check-health|check-security|check-rbac) ;;
    *) die_usage "Invalid --action '${1}'. Expected one of: plan, apply, status, show-urls, check-health, check-security, check-rbac" ;;
  esac
}

action_uses_stage() {
  case "$1" in
    plan|apply|check-health|check-security|check-rbac) return 0 ;;
    status|show-urls) return 1 ;;
    *) return 1 ;;
  esac
}

default_profiles_dir() {
  printf '%s/kubernetes/%s/profiles\n' "${REPO_ROOT}" "${TARGET}"
}

save_profile_path() {
  printf '%s/%s.tfvars\n' "${PROFILES_DIR}" "${SAVE_PROFILE_NAME}"
}

validate_profile_name() {
  local name="$1"

  if [[ ! "${name}" =~ ^[A-Za-z0-9._-]+$ ]]; then
    die_usage "Invalid --profile-name '${name}'. Use letters, numbers, dot, underscore, or hyphen"
  fi
}

normalize_app_value() {
  case "$1" in
    on|true|1|yes) printf 'true' ;;
    off|false|0|no) printf 'false' ;;
    *) return 1 ;;
  esac
}

set_app_override() {
  local spec="$1"
  local app="${spec%%=*}"
  local raw_value="${spec#*=}"
  local value=""

  if [[ "${app}" = "${spec}" || -z "${raw_value}" ]]; then
    die_usage "Invalid --app '${spec}'. Expected name=on|off"
  fi

  value="$(normalize_app_value "${raw_value}")" || die_usage "Invalid --app '${spec}'. Expected value on|off"

  case "${app}" in
    sentiment) APP_SENTIMENT="${value}" ;;
    subnetcalc) APP_SUBNETCALC="${value}" ;;
    *) die_usage "Invalid --app '${app}'. Expected one of: sentiment, subnetcalc" ;;
  esac
}

default_tfvars_file() {
  printf '%s/.run/operator/%s-stage%s.tfvars\n' "${REPO_ROOT}" "${TARGET}" "${STAGE}"
}

has_tfvars_overrides() {
  [[ -n "${APP_SENTIMENT}" || -n "${APP_SUBNETCALC}" ]]
}

render_tfvars() {
  printf '# Generated by scripts/platform-workflow.sh; safe to delete.\n'
  printf '# Target: %s, stage: %s\n\n' "${TARGET}" "${STAGE}"
  if [[ -n "${APP_SENTIMENT}" ]]; then
    printf 'enable_app_repo_sentiment = %s\n' "${APP_SENTIMENT}"
  fi
  if [[ -n "${APP_SUBNETCALC}" ]]; then
    printf 'enable_app_repo_subnetcalc = %s\n' "${APP_SUBNETCALC}"
  fi
}

write_tfvars_if_needed() {
  has_tfvars_overrides || return 0
  mkdir -p "$(dirname "${TFVARS_FILE}")"
  render_tfvars >"${TFVARS_FILE}"
}

build_command_args() {
  local stack_path="$1"
  WORKFLOW_COMMAND_ARGS=()
  if has_tfvars_overrides; then
    if [[ "${#WORKFLOW_COMMAND_ARGS[@]}" -eq 0 ]]; then
      WORKFLOW_COMMAND_ARGS+=(env)
    fi
    WORKFLOW_COMMAND_ARGS+=("PLATFORM_TFVARS=${TFVARS_FILE}")
  fi
  WORKFLOW_COMMAND_ARGS+=(make -C "${stack_path}")
  if [[ "${TARGET}:${STAGE}" = "kind:950-local-idp" ]]; then
    WORKFLOW_COMMAND_ARGS+=("950-local-idp")
  elif action_uses_stage "${ACTION}"; then
    WORKFLOW_COMMAND_ARGS+=("${STAGE}")
  fi
  WORKFLOW_COMMAND_ARGS+=("${ACTION}")
  if [[ "${AUTO_APPROVE}" = "1" ]]; then
    WORKFLOW_COMMAND_ARGS+=(AUTO_APPROVE=1)
  fi
}

command_string() {
  shell_cli_print_command "${WORKFLOW_COMMAND_ARGS[@]}"
}

print_options() {
  case "${OUTPUT_FORMAT}" in
    text)
      cat <<'EOF'
Targets:
  kind
  lima
  slicer

Stages:
  100 cluster
  200 cilium
  300 hubble
  400 argocd
  500 gitea
  600 policies
  700 app-repos
  800 observability
  900 sso
  950-local-idp local-idp

Actions:
  plan
  apply
  status
  show-urls
  check-health
  check-security
  check-rbac

App toggles:
  sentiment=on|off
  subnetcalc=on|off

EOF
      ;;
    json)
      jq -n '{
        targets: ["kind", "lima", "slicer"],
        stages: [
          {id:"100", label:"cluster"},
          {id:"200", label:"cilium"},
          {id:"300", label:"hubble"},
          {id:"400", label:"argocd"},
          {id:"500", label:"gitea"},
          {id:"600", label:"policies"},
          {id:"700", label:"app-repos"},
          {id:"800", label:"observability"},
          {id:"900", label:"sso"},
          {id:"950-local-idp", label:"local-idp", target:"kind"}
        ],
        actions: ["plan", "apply", "status", "show-urls", "check-health", "check-security", "check-rbac"],
        apps: ["sentiment", "subnetcalc"],
        profiles: []
      }'
      ;;
    *) die_usage "Invalid --output '${OUTPUT_FORMAT}'. Expected text or json" ;;
  esac
}

print_preview() {
  local stack_path="$1"
  local command=""
  command="$(command_string)"

  case "${OUTPUT_FORMAT}" in
    text)
      printf 'Target: %s (%s)\n' "${TARGET}" "${stack_path}"
      printf 'Stage: %s\n' "${STAGE}"
      printf 'Action: %s\n' "${ACTION}"
      if has_tfvars_overrides; then
        printf 'Generated tfvars: %s\n' "${TFVARS_FILE}"
        printf '\n'
        render_tfvars
        printf '\n'
      else
        printf 'Generated tfvars: none\n\n'
      fi
      printf 'Command:\n  %s\n' "${command}"
      ;;
    json)
      jq -n \
        --arg target "${TARGET}" \
        --arg stack_path "${stack_path}" \
        --arg stage "${STAGE}" \
        --arg action "${ACTION}" \
        --arg tfvars_file "$(has_tfvars_overrides && printf '%s' "${TFVARS_FILE}")" \
        --arg command "${command}" \
        --argjson has_tfvars "$(has_tfvars_overrides && printf true || printf false)" \
        --argjson app_sentiment "$(if [[ -n "${APP_SENTIMENT}" ]]; then printf '%s' "${APP_SENTIMENT}"; else printf null; fi)" \
        --argjson app_subnetcalc "$(if [[ -n "${APP_SUBNETCALC}" ]]; then printf '%s' "${APP_SUBNETCALC}"; else printf null; fi)" \
        '{
          target: $target,
          stack_path: $stack_path,
          stage: $stage,
          action: $action,
          profile: {name: null, path: null},
          tfvars_file: (if $has_tfvars then $tfvars_file else null end),
          app_overrides: {
            sentiment: $app_sentiment,
            subnetcalc: $app_subnetcalc
          },
          command: $command
        }'
      ;;
    *) die_usage "Invalid --output '${OUTPUT_FORMAT}'. Expected text or json" ;;
  esac
}

save_profile() {
  local output_path=""

  if [[ -z "${SAVE_PROFILE_NAME}" ]]; then
    die_usage "Missing --profile-name for save-profile"
  fi
  validate_profile_name "${SAVE_PROFILE_NAME}"
  if ! has_tfvars_overrides; then
    die_usage "save-profile requires at least one --app override"
  fi
  if [[ -z "${PROFILES_DIR}" ]]; then
    PROFILES_DIR="$(default_profiles_dir)"
  fi

  output_path="$(save_profile_path)"
  mkdir -p "${PROFILES_DIR}"
  render_tfvars >"${output_path}"

  case "${OUTPUT_FORMAT}" in
    text)
      printf 'Saved profile: %s\n' "${output_path}"
      ;;
    json)
      jq -n \
        --arg target "${TARGET}" \
        --arg name "${SAVE_PROFILE_NAME}" \
        --arg path "${output_path}" \
        '{saved_profile:{target:$target,name:$name,path:$path}}'
      ;;
    *) die_usage "Invalid --output '${OUTPUT_FORMAT}'. Expected text or json" ;;
  esac
}

SUBCOMMAND=""
LEADING_STANDARD_FLAGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run|--execute)
      LEADING_STANDARD_FLAGS+=("$1")
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      SUBCOMMAND="$1"
      shift
      break
      ;;
  esac
done
if [[ "${#LEADING_STANDARD_FLAGS[@]}" -gt 0 ]]; then
  set -- "${LEADING_STANDARD_FLAGS[@]}" "$@"
fi

case "${SUBCOMMAND}" in
  options|preview|apply|save-profile) ;;
  -h|--help|'')
    usage
    exit 0
    ;;
  *)
    die_usage "Unknown subcommand '${SUBCOMMAND}'. Expected options, preview, apply, or save-profile"
    ;;
esac

shell_cli_init_standard_flags
while [[ $# -gt 0 ]]; do
  if shell_cli_handle_standard_flag usage "$1"; then
    shift
    continue
  fi

  case "$1" in
    --target)
      require_value "$1" "${2-}"
      TARGET="$2"
      shift 2
      ;;
    --stage)
      require_value "$1" "${2-}"
      STAGE="$2"
      shift 2
      ;;
    --action)
      require_value "$1" "${2-}"
      ACTION="$2"
      shift 2
      ;;
    --profile)
      die_usage "--profile has been removed; use --stage 950-local-idp for the local IDP target"
      ;;
    --profile-name)
      require_value "$1" "${2-}"
      SAVE_PROFILE_NAME="$2"
      shift 2
      ;;
    --profiles-dir)
      require_value "$1" "${2-}"
      PROFILES_DIR="$2"
      shift 2
      ;;
    --app)
      require_value "$1" "${2-}"
      set_app_override "$2"
      shift 2
      ;;
    --tfvars-file)
      require_value "$1" "${2-}"
      TFVARS_FILE="$2"
      shift 2
      ;;
    --auto-approve)
      AUTO_APPROVE="1"
      shift
      ;;
    --output)
      require_value "$1" "${2-}"
      OUTPUT_FORMAT="$2"
      shift 2
      ;;
    *)
      shell_cli_unknown_flag "$(shell_cli_script_name)" "$1"
      exit 2
      ;;
  esac
done

validate_target "${TARGET}"
validate_stage "${STAGE}"
validate_action "${ACTION}"

if [[ -z "${TFVARS_FILE}" ]]; then
  TFVARS_FILE="$(default_tfvars_file)"
fi

STACK_PATH="$(target_path "${TARGET}")"
build_command_args "${STACK_PATH}"

if [[ "${SHELL_CLI_DRY_RUN}" -eq 1 ]]; then
  shell_cli_print_dry_run_summary "would build ${TARGET} stage ${STAGE} ${ACTION} workflow"
  print_preview "${STACK_PATH}"
  exit 0
fi

if [[ "${SHELL_CLI_EXECUTE}" -ne 1 ]]; then
  usage
  shell_cli_print_dry_run_summary "would build ${TARGET} stage ${STAGE} ${ACTION} workflow"
  exit 0
fi

case "${SUBCOMMAND}" in
  options)
    print_options
    ;;
  preview)
    write_tfvars_if_needed
    print_preview "${STACK_PATH}"
    ;;
  apply)
    write_tfvars_if_needed
    print_preview "${STACK_PATH}" >&2
    exec "${WORKFLOW_COMMAND_ARGS[@]}"
    ;;
  save-profile)
    save_profile
    ;;
esac
