apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnp-platform-gateway-observed-egress-candidate
  namespace: platform-gateway
  annotations:
    "policies.cilium.io/title": "Platform Gateway observed egress candidate"
    "platform.publiccloudexperiments.net/source-kind": "CiliumNetworkPolicy"
    "platform.publiccloudexperiments.net/hubble-policy-candidate": "true"
    "platform.publiccloudexperiments.net/hubble-policy-direction": "egress"
    "platform.publiccloudexperiments.net/hubble-policy-mode": "workload"
    "platform.publiccloudexperiments.net/hubble-policy-row-count": "3"
    "platform.publiccloudexperiments.net/hubble-policy-since": "5m"
    "platform.publiccloudexperiments.net/hubble-policy-iterations": "3"
    "platform.publiccloudexperiments.net/hubble-policy-capture-mode": "flows"
specs:
  - description: >-
      Observed egress traffic from platform-gateway/platform-gateway-nginx
    endpointSelector:
      matchLabels:
        "k8s:io.kubernetes.pod.namespace": "platform-gateway"
        "k8s:app.kubernetes.io/name": "platform-gateway-nginx"
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": "nginx-gateway"
              "k8s:app.kubernetes.io/name": "nginx-gateway"
        toPorts:
          - ports:
              - port: "8443"
                protocol: TCP
