config:
  power_events: true
  host_groups:
    - name: sbox
      count: 1
      vcpu: 4
      ram_gb: 12
      storage_size: 20G
      share_home: ""
      rosetta: false
      sleep_action: prevent
      network:
        mode: nat
        gateway: 192.168.64.1/24

  image: "ghcr.io/openfaasltd/slicer-systemd-2404-arm64-avz:6.12.70-aarch64-avz-latest"
  hypervisor: apple
  api:
    socket: "/Users/nickromney/Developer/personal/platform/kubernetes/slicer/.run/slicer.sock"
