# Generated by kubernetes/kind/scripts/render-operator-overrides.sh
# KIND_WORKER_COUNT counts worker nodes. Total kind nodes = workers + 1 control-plane.
worker_count = 1
# KIND_ENABLE_BACKSTAGE=on
enable_backstage = true
enable_image_preload = false
enable_apps_dir_mount = false
enable_docker_socket_mount = false
enable_actions_runner = false
prefer_external_platform_images = true
external_platform_image_refs = {
  backstage                            = "host.docker.internal:5002/platform/backstage:src-6688e4af42db9d2f142b"
  grafana                              = "host.docker.internal:5002/platform/grafana-victorialogs:12.3.1-v0.28.0"
  "idp-core"                           = "host.docker.internal:5002/platform/idp-core:src-b5557cc9e951fe1c4fb3"
  "platform-mcp"                       = "host.docker.internal:5002/platform/platform-mcp:src-529dc0086e31dbcb745e"
  "chatgpt-sim"                        = "host.docker.internal:5002/platform/chatgpt-sim:src-bdbbeed738bf3aefbe03"
  "langfuse-demos"                     = "host.docker.internal:5002/platform/langfuse-demos:src-5db5ca8eaccdfb22a689"
}
prefer_external_workload_images = true
external_workload_image_refs = {
  "sentiment-api"                      = "host.docker.internal:5002/platform/sentiment-api:src-9c81cc10c15d0e5212ab"
  "sentiment-auth-ui"                  = "host.docker.internal:5002/platform/sentiment-auth-ui:src-9c81cc10c15d0e5212ab"
  "subnetcalc-api"                     = "host.docker.internal:5002/platform/subnetcalc-api:src-ef9b45fc5f7d5af9ac72"
  "subnetcalc-apim-simulator"          = "host.docker.internal:5002/platform/subnetcalc-apim-simulator:src-2716fb72afef6fbcfa7b"
  "subnetcalc-frontend"                = "host.docker.internal:5002/platform/subnetcalc-frontend:src-ef9b45fc5f7d5af9ac72"
}
