apiVersion: v1
kind: Service
metadata:
  name: subnetcalc-frontend-canary
  labels:
    app.kubernetes.io/name: subnetcalc-frontend
    app.kubernetes.io/component: frontend
    app: subnetcalc
    project: kindlocal
    team: dolphin
    tier: frontend
    role: frontend
spec:
  selector:
    app.kubernetes.io/name: subnetcalc-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      appProtocol: http
      port: 8080
      targetPort: http
