#!/bin/sh
set -eu

API_BASE_URL="${API_BASE_URL:-http://localhost:8000}"
APIM_SUBSCRIPTION_KEY="${APIM_SUBSCRIPTION_KEY:-todo-demo-key}"
GRAFANA_BASE_URL="${GRAFANA_BASE_URL:-http://localhost:3001}"
OBSERVABILITY_DASHBOARD_URL="${OBSERVABILITY_DASHBOARD_URL:-${GRAFANA_BASE_URL%/}/d/apim-simulator-overview/apim-simulator-overview}"
TEMPLATE_PATH="${RUNTIME_CONFIG_TEMPLATE_PATH:-/opt/runtime-config.template.js}"
OUTPUT_PATH="${RUNTIME_CONFIG_OUTPUT_PATH:-/tmp/runtime-config.js}"

export API_BASE_URL
export APIM_SUBSCRIPTION_KEY
export GRAFANA_BASE_URL
export OBSERVABILITY_DASHBOARD_URL

mkdir -p "$(dirname "$OUTPUT_PATH")"

envsubst '${API_BASE_URL} ${APIM_SUBSCRIPTION_KEY} ${GRAFANA_BASE_URL} ${OBSERVABILITY_DASHBOARD_URL}' \
  < "$TEMPLATE_PATH" \
  > "$OUTPUT_PATH"
