app:
  title: Portal
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: ${BACKSTAGE_BASE_URL}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: ${BACKSTAGE_BASE_URL}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'
  cors:
    origin: ${BACKSTAGE_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  database:
    client: better-sqlite3
    connection:
      directory: /tmp/backstage

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  environment: production
  providers:
    oauth2Proxy:
      signIn:
        resolvers:
          - resolver: emailMatchingUserEntityProfileEmail

catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  locations:
    - type: file
      target: ./catalog/entities.yaml

    - type: file
      target: ./catalog/apps/platform-mcp/catalog-info.yaml

    - type: file
      target: ./catalog/apps/subnetcalc/catalog-info.yaml

    - type: file
      target: ./catalog/apps/apim-simulator/catalog-info.yaml

    - type: file
      target: ./catalog/apps/sentiment/catalog-info.yaml

    - type: file
      target: ./catalog/templates/platform-service/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./catalog/org.yaml
      rules:
        - allow: [User, Group]

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: local
          url: https://kubernetes.default.svc
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: true
