# Generated by scripts/platform-workflow.sh; safe to delete.
# Variant: kind, stage: 900

# Source: preset resource-profile=local-idp-12gb
enable_argocd = true

# Source: preset resource-profile=local-idp-12gb
enable_gitea = true

# Source: preset resource-profile=local-idp-12gb
enable_gateway_tls = true

# Source: preset resource-profile=local-idp-12gb
enable_cert_manager = true

# Source: preset resource-profile=local-idp-12gb
enable_sso = true

# Source: preset resource-profile=local-idp-12gb
sso_provider = "keycloak"

# Source: preset resource-profile=local-idp-12gb
enable_argocd_oidc = true

# Source: preset resource-profile=local-idp-12gb
enable_app_of_apps = false

# Source: preset resource-profile=local-idp-12gb
argocd_applicationset_enabled = false

# Source: preset resource-profile=local-idp-12gb
argocd_notifications_enabled = false

# Source: preset resource-profile=local-idp-12gb
enable_app_repo_sentiment = true

# Source: preset resource-profile=local-idp-12gb
enable_app_repo_subnetcalc = false

# Source: preset resource-profile=local-idp-12gb
enable_backstage = true

# Source: preset resource-profile=local-idp-12gb
enable_host_local_registry = true

# Source: preset resource-profile=local-idp-12gb
host_local_registry_host = "host.docker.internal:5002"

# Source: preset resource-profile=local-idp-12gb
host_local_registry_scheme = "http"

# Source: preset resource-profile=local-idp-12gb
prefer_external_platform_images = true

# Source: preset resource-profile=local-idp-12gb
prefer_external_workload_images = true

# Source: preset resource-profile=local-idp-12gb
enable_actions_runner = false

# Source: preset resource-profile=local-idp-12gb
enable_apps_dir_mount = false

# Source: preset resource-profile=local-idp-12gb
enable_docker_socket_mount = false

# Source: preset resource-profile=local-idp-12gb
external_platform_image_refs = {
  backstage = "host.docker.internal:5002/platform/backstage:1.0.0"
  "idp-core" = "host.docker.internal:5002/platform/idp-core:0.1.0"
}

# Source: preset resource-profile=local-idp-12gb
external_workload_image_refs = {
  "sentiment-api" = "host.docker.internal:5002/platform/sentiment-api:0.1.0"
  "sentiment-auth-ui" = "host.docker.internal:5002/platform/sentiment-auth-ui:0.1.0"
}

# Source: preset resource-profile=local-idp-12gb
enable_signoz = false

# Source: preset resource-profile=local-idp-12gb
enable_prometheus = false

# Source: preset resource-profile=local-idp-12gb
enable_grafana = false

# Source: preset resource-profile=local-idp-12gb
enable_loki = false

# Source: preset resource-profile=local-idp-12gb
enable_victoria_logs = false

# Source: preset resource-profile=local-idp-12gb
enable_tempo = false

# Source: preset resource-profile=local-idp-12gb
enable_observability_agent = false

# Source: preset resource-profile=local-idp-12gb
enable_headlamp = false

# Source: preset image-distribution=local-cache
enable_host_local_registry = true

# Source: preset image-distribution=local-cache
host_local_registry_scheme = "http"

# Source: preset image-distribution=local-cache
host_local_registry_host = "host.docker.internal:5002"

# Source: preset observability-stack=lgtm
enable_prometheus = true

# Source: preset observability-stack=lgtm
enable_grafana = true

# Source: preset observability-stack=lgtm
enable_loki = true

# Source: preset observability-stack=lgtm
enable_tempo = true

# Source: preset observability-stack=lgtm
enable_victoria_logs = false

# Source: preset identity-stack=dex
sso_provider = "dex"

# Source: preset app-set=no-reference-apps
enable_app_repo_sentiment = false

# Source: preset app-set=no-reference-apps
enable_app_repo_subnetcalc = false

# Source: custom app override
enable_app_repo_sentiment = false

# Source: custom app override
enable_app_repo_subnetcalc = true

# Source: custom override
worker_count = 2

