apiVersion: v1
kind: Namespace
metadata:
  name: idp
  labels:
    platform.publiccloudexperiments.net/namespace-role: platform
    platform.publiccloudexperiments.net/sensitivity: internal
    kyverno.io/isolate: "true"
